language: scala

scala:
  - 2.12.16
  - 2.11.11

env:
  - JDK=openjdk6
  - JDK=openjdk7
  - JDK=oraclejdk7
  - JDK=oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION "test"

before_script:
  - jdk_switcher use $JDK

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.16
      env: JDK=openjdk6
    - scala: 2.12.16
      env: JDK=openjdk7
    - scala: 2.12.16
      env: JDK=oraclejdk7
